site_name: wcarlsen's blog
site_url: https://wcarlsen.github.io/
theme:
  name: material
  font:
    text: JetBrains Mono
    code: JetBrains Mono
  logo: assets/logo.png
  features:
    - header.autohide
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - blog:
      blog_dir: .
      blog_toc: true
      post_url_format: "{file}"
      authors: false
  - search
  - tags
  - rss:
      match_path: posts/.*
      date_from_meta:
        as_creation: date
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/wcarlsen
      name: wcarlsen
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/wcarlsen/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/willicarl/
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
