name: renovate
on:
  schedule:
    - cron: "00 8 * * 1,5" # At 08:00 on Monday and Friday
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.4
        env:
          LOG_LEVEL: ${{ vars.LOG_LEVEL || 'info' }}
          RENOVATE_INTERNAL_CHECKS_FILTER: none
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
          repositories: {{ github.event.repository.name }}
